CHAR:
	PUSH(FP);
	MOV(FP, SP);
	MOV(R0, FPARG(IMM(2)));
	CMP(IND(R0), IMM(T_CHAR));
	JUMP_NE(CHAR_NOT_CHAR);
	MOV(R0, IMM(14));
	JUMP(CHAR_EXIT);
	CHAR_NOT_CHAR:
	MOV(R0, IMM(12));
	CHAR_EXIT:
	POP(FP);
	RETURN;