INTEGER:
	PUSH(FP);
	MOV(FP, SP);
	MOV(R0, FPARG(IMM(2)));
	CMP(IND(R0), IMM(T_INTEGER));
	JUMP_NE(INTEGER_NOT_INTEGER);
	MOV(R0, IMM(14));
	JUMP(INTEGER_EXIT);
	INTEGER_NOT_INTEGER:
	MOV(R0, IMM(12));
	INTEGER_EXIT:
	POP(FP);
	RETURN;