MAKE_VECTOR:
   PUSH(FP);
   MOV(FP, SP);
   PUSH(R1);
   PUSH(R2);
   
   CMP(FPARG(IMM(1)), IMM(2));
   JUMP_NE(OBJ_UNSPECIFIED);
   MOV(R0, FPARG(IMM(3)));
   JUMP(MAKE_VECTOR_BEFORE_LOOP);
   
OBJ_UNSPECIFIED:
   MOV(R0, IMM(11)); // Null
   
MAKE_VECTOR_BEFORE_LOOP:
   MOV(R1, FPARG(IMM(2)));
   MOV(R1, INDD(R1, 1));
   MOV(R2, R1);
   
MAKE_VECTOR_LOOP:
   CMP(R1, IMM(0));
   JUMP_EQ(MAKE_VECTOR_EXIT_LOOP);
   PUSH(R0);
   DECR(R1);
   JUMP(MAKE_VECTOR_LOOP);
   
MAKE_VECTOR_EXIT_LOOP:
   PUSH(R2);
   CALL(MAKE_SOB_VECTOR);
   DROP(R2);
   DROP(IMM(1));
   
   POP(R2);
   POP(R1);
   POP(FP);
   RETURN;
   