NUMBER:
	PUSH(FP);
	MOV(FP, SP);
	MOV(R0, FPARG(IMM(2)));
	CMP(IND(R0), IMM(T_INTEGER));
	JUMP_NE(NUMBER_NOT_NUMBER);
	MOV(R0, IMM(14));
	JUMP(NUMBER_EXIT);
	NUMBER_NOT_NUMBER:
	MOV(R0, IMM(12));
	NUMBER_EXIT:
	POP(FP);
	RETURN;