PAIR:
	PUSH(FP);
	MOV(FP, SP);
	MOV(R0, FPARG(IMM(2)));
	CMP(IND(R0), IMM(T_PAIR));
	JUMP_NE(PAIR_NOT_PAIR);
	MOV(R0, IMM(14));
	JUMP(PAIR_EXIT);
	PAIR_NOT_PAIR:
	MOV(R0, IMM(12));
	PAIR_EXIT:
	POP(FP);
	RETURN;