PRIM_NULL:
	PUSH(FP);
	MOV(FP, SP);
	
	MOV(R0, FPARG(IMM(2)));
	CMP(IND(R0), IMM(T_NIL));
	JUMP_NE(PRIM_NULL_NOT_NIL);
	MOV(R0, IMM(14));
	JUMP(PRIM_NULL_EXIT);
PRIM_NULL_NOT_NIL:
	MOV(R0, IMM(12));

PRIM_NULL_EXIT:
	POP(FP);
	RETURN;