PRIM_EQ:
	PUSH(FP);
	MOV(FP, SP);
	PUSH(R1);
	PUSH(R2);
	
	MOV(R1, FPARG(2));
	MOV(R2, FPARG(3));
	
	CMP(IND(R1), IND(R2));
	JUMP_NE(EQ_NOT_EQ);

	CMP(IND(R1), IMM(T_INTEGER));
	JUMP_EQ(EQ_COMPARE_FIELDS);
	CMP(IND(R1), IMM(T_SYMBOL));
	JUMP_EQ(EQ_COMPARE_FIELDS);
	CMP(IND(R1), IMM(T_CHAR));
	JUMP_EQ(EQ_COMPARE_FIELDS);
	CMP(IND(R1), IMM(T_PAIR));
	JUMP_EQ(EQ_COMPARE_ADDRESSES);
	CMP(IND(R1), IMM(T_BOOL));
	JUMP_EQ(EQ_COMPARE_ADDRESSES);
	CMP(IND(R1), IMM(T_VOID));
	JUMP_EQ(EQ_COMPARE_ADDRESSES);
	CMP(IND(R1), IMM(T_VECTOR));
	JUMP_EQ(EQ_COMPARE_ADDRESSES);
	CMP(IND(R1), IMM(T_STRING));
	JUMP_EQ(EQ_COMPARE_ADDRESSES);
	CMP(IND(R1), IMM(T_NIL));
	
EQ_COMPARE_ADDRESSES:
	CMP(R1, R2);
	JUMP_EQ(EQ_ARE_EQ);
	JUMP(EQ_NOT_EQ)
	
EQ_COMPARE_FIELDS:
	CMP(INDD(R1, 1), INDD(R2, 1));
	JUMP_EQ(EQ_ARE_EQ);
	
EQ_NOT_EQ:
	MOV(R0, IMM(12)) // false
	JUMP(PRIM_EQ_EXIT);
	
EQ_ARE_EQ:
	MOV(R0, IMM(14)) // true
	
PRIM_EQ_EXIT:
	POP(R2);
	POP(R1);
	POP(FP);
	RETURN;
	