SYMBOL:
	PUSH(FP);
	MOV(FP, SP);
	MOV(R0, FPARG(IMM(2)));
	CMP(IND(R0), IMM(T_SYMBOL));
	JUMP_NE(SYMBOL_NOT_SYMBOL);
	MOV(R0, IMM(14));
	JUMP(SYMBOL_EXIT);
	SYMBOL_NOT_SYMBOL:
	MOV(R0, IMM(12));
	SYMBOL_EXIT:
	POP(FP);
	RETURN;